ContractAddressHex to contract address
0xSpaceShard/starknet-devnet-rs pull request #118
Opened 2023-08-01 07:01 UTC by taco-paco

## Usage related changes

## Development related changes

## Checklist:

- [x  ] Applied formatting - `./scripts/format.sh`
- [ x ] No linter errors - `./scripts/clippy_check.sh`
- [ x ] Performed code self-review
- [ x ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [ ] Linked the issues which this PR resolves
- [x  ] Updated the tests
- [ x] All tests are passing - `cargo test`

2023-08-01 07:58 UTC, marioiordanov requested changes

2023-08-01 07:58 UTC, marioiordanov commented on crates/types/src/serde_helpers.rs
why `mod empty_params` is moved to the types project. Shouldn't it be left in the `starknet-server`?

2023-08-08 06:13 UTC, taco-paco commented on crates/types/src/serde_helpers.rs
fixed

2023-08-08 06:24 UTC, marioiordanov approved these changes

2023-08-08 08:38 UTC, FabijanC approved these changes
CI workflow is passing

2023-08-09 10:11 UTC, merged