Fix account balance overflow
0xSpaceShard/starknet-devnet-rs pull request #377
Opened 2024-03-12 03:04 UTC by JimmyFate

Closes #110 

## Usage related changes

- amount must be a string instead of plain integer in `/mint`

## Development related changes

- [add primitive-types](https://github.com/0xSpaceShard/starknet-devnet-rs/commit/66f5c8014f919ac8c901b1e2e83003a7a9ccf737)
- [change balance to u256](https://github.com/0xSpaceShard/starknet-devnet-rs/commit/f484e434f1c68c669d27c2c7a20d0647067e5520)

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] No unused dependencies - `./scripts/check_unused_deps.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [x] Linked the issues which this PR resolves
- [x] Checked the TODO section in README.md if this PR resolves it
- [x] Updated the tests
- [ ] All tests are passing - `cargo test`

---

These 2 tests are failing locally for me:

```sh
failures:
    test_messaging::can_deploy_l1_messaging_contract
    test_messaging::can_interact_with_l1
```

2024-03-12 09:30 UTC, FabijanC requested changes
1. Why do we need a new dependency for all this (`primitive_types::U256`)? Can't we use the existing `BigUint`?
2. I don't know if we want to introduce the breaking semantic change of requiring a string instead of a number in the /mint endpoint. Can't we deserialize a big numeric JSON literal into the desired numeric Rust type (be it U256 or BigUint), without it needing to be a string?

cc: @marioiordanov

2024-03-12 12:11 UTC, JimmyFate commented
> 1. Why do we need a new dependency for all this (`primitive_types::U256`)? Can't we use the existing `BigUint`?

It'd require creating a custom `U256` struct wrapping the `BigUint`, with other impls, bloating the codebase. I feel like it's better to just use an existing one.

> 2. I don't know if we want to introduce the breaking semantic change of requiring a string instead of a number in the /mint endpoint. Can't we deserialize a big numeric JSON literal into the desired numeric Rust type (be it U256 or BigUint), without it needing to be a string?

Rust's built-in numeric types only go up to u128, so there's no built-in way to deserialize a u256 directly. I've you have any idea on how to do this, I'm down to change it.

2024-03-13 13:54 UTC, marioiordanov commented on crates/starknet-devnet-core/src/account.rs
> +    #[allow(dead_code)]
If those functions are marked with 'dead_code' why not remove them

2024-03-13 15:08 UTC, marioiordanov commented
> > 1. Why do we need a new dependency for all this (`primitive_types::U256`)? Can't we use the existing `BigUint`?
> 
> It'd require creating a custom `U256` struct wrapping the `BigUint`, with other impls, bloating the codebase. I feel like it's better to just use an existing one.
> 
> > 2. I don't know if we want to introduce the breaking semantic change of requiring a string instead of a number in the /mint endpoint. Can't we deserialize a big numeric JSON literal into the desired numeric Rust type (be it U256 or BigUint), without it needing to be a string?
> 
> Rust's built-in numeric types only go up to u128, so there's no built-in way to deserialize a u256 directly. I've you have any idea on how to do this, I'm down to change it.

It's possible for deserialising directly from some number. Just deserialize to serde_json::Value::Number

2024-03-13 15:15 UTC, FabijanC commented
> It's possible for deserialising directly from some number. Just deserialize to serde_json::Value::Number. Then convert to string and then convert to U256

I ran an experiment and it seems that precision is lost that way: [experiment link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=209a2e26733e62781a1f2f390da0ca1a)

2024-03-13 15:18 UTC, marioiordanov commented
> experiment link

The experiment doesn't emulate starknet-devnet-rs, because it uses arbitrary precision in the crate that the file is

2024-03-13 15:25 UTC, FabijanC commented
> > experiment link
> 
> The experiment doesn't emulate starknet-devnet-rs, because it uses arbitrary precision in the crate that the file is

Wow, didn't know that. I ran the code as a devnet test and indeede the precision is preserved.

2024-03-19 00:26 UTC, JimmyFate commented
> It's possible for deserialising directly from some number. Just deserialize to serde_json::Value::Number. Then convert to string and then convert to U256

Thanks for the great tip @marioiordanov! Didn't know that.
Done as pointed out 👍

2024-03-19 08:24 UTC, FabijanC reviewed
Can we now lose the U256 dependency?

2024-03-19 23:31 UTC, JimmyFate commented
> Can we now lose the U256 dependency?

Could `ethers` be used instead or do you insist on a separate own struct for U256? `starknet-devnet-core` already uses it (it uses `primitive-types` itself too)

2024-03-20 08:04 UTC, marioiordanov approved these changes

2024-03-20 08:09 UTC, FabijanC approved these changes
> > Can we now lose the U256 dependency?
> 
> Could `ethers` be used instead or do you insist on a separate own struct for U256? `starknet-devnet-core` already uses it (it uses `primitive-types` itself too)

I meant losing the `primitive-types` dependency. But I guess an extra dependency is not such a big issue; your PR is good, so let's merge it. Thank you for the contribution and the patience.

2024-03-20 08:10 UTC, merged