lite-mode initialized
0xSpaceShard/starknet-devnet-rs pull request #444
Opened 2024-04-25 11:37 UTC by lordshashank

## Usage related changes

Would implement lite node that can be used with "--lite-node" tag which would skip blockhash calculation by replacing it with block_number hashes.

## Development related changes

Resolves https://github.com/0xSpaceShard/starknet-devnet-rs/issues/343

## Checklist:

- [ ] Checked the relevant parts of [development docs](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#development)
- [X] Applied formatting - `./scripts/format.sh`
- [X] No linter errors - `./scripts/clippy_check.sh`
- [X] No unused dependencies - `./scripts/check_unused_deps.sh`
- [X] Performed code self-review
- [X] Rebased to the latest commit of the target branch (or merged it into my branch)
- [ ] Updated the docs if needed, including the [TODO section](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#todo-to-reach-feature-parity-with-the-pythonic-devnet)
- [X] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) which this PR resolves
- [ ] Updated the tests if needed; all passing ([execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#test-execution))

2024-04-25 11:47 UTC, lordshashank commented
@ivpavici I have implemented lite mode by skipping blockhash calculation [here](https://github.com/0xSpaceShard/starknet-devnet-rs/pull/444/files#diff-c3e1711bf66de593f5875f51b8500529fc04c7a785ffb1c499b0407b69f6cc9aR279) and replacing it with hash of block_number. 

Could you please see if the implementation is correct, I am not sure of few things like would calculating [block_number](https://github.com/0xSpaceShard/starknet-devnet-rs/pull/444/files#diff-c3e1711bf66de593f5875f51b8500529fc04c7a785ffb1c499b0407b69f6cc9aR275) before initializing header cause problem?, validity of initializing hash with ```from_prefixed_hex_string(block_number_hex)``` to reduce computation than ```generate_hex()```, or if I have went completely wrong way here. 

Also let me know if hash calculation has to be skipped somewhere else as well, thanks.

2024-04-25 13:35 UTC, FabijanC reviewed
Have you done any benchmarking? What is the time impact of skipping block hash calculation?

2024-04-25 13:38 UTC, lordshashank commented
Not yet, I just implemented the functionality as per devnet-py, if its required let me know how I can do that?

2024-04-25 13:52 UTC, FabijanC commented
> Not yet, I just implemented the functionality as per devnet-py, if its required let me know how I can do that?

Think of something, be creative :D

But one test could look like this, let's call the script `mint_benchmark.sh`:
```bash
#!/bin/bash

set -eu

N=$1

for _ in $(seq 1 $N); do
    curl -w "\n" -sSf localhost:5050/mint --json '{
        "amount": 1,
        "address": "0x1"
    }'
done
```

And you could run:
```
$ chmod +x mint_benchmark.sh
$ time ./mint_benchmark.sh 1000
```

Or replace 1000 with any number you wish to test. Of course, this assumes that somewhere on your computer you have Devnet running at port 5050. I'd recommend testing both `cargo run` and `cargo run --release`, both in lite and regular mode.

2024-04-25 14:56 UTC, ivpavici commented
yeah, please @lordshashank we would be very grateful for this test and report afterwards :)

2024-05-01 11:42 UTC, lordshashank commented
@FabijanC @ivpavici I have added benchmark report and test file as well, let me know if something else is needed.

2024-05-02 12:46 UTC, ivpavici commented
thanks!
Seems like the speedup is negligible in  `--release` mode... I will let @FabijanC decide about the merging. But either way this was helpful for us so you will definitely get a reward regardless if we merge or not!

2024-05-02 15:09 UTC, FabijanC requested changes
Thanks for the table report in the PR description! How did you accumulate the times? I mean - are you reporting what you got on the first run? Or did you run it multiple times?

Also, I'm having doubts about DX and UX and if `--lite-mode` is the best approach. Perhaps we should have multiple CLI options like `--block-hash <REAL|DUMMY>`. We should consider what else can be skipped (other than block hash generation).

2024-05-02 15:09 UTC, FabijanC commented on README.md
> +## Lite mode
```suggestion
## Lite Mode
```

2024-05-02 15:09 UTC, FabijanC commented on README.md
> +Runs the Devnet in a minimal lite mode by just skipping the block hash calculation. This is useful for testing purposes when the block hash is not needed.
```suggestion
Runs Devnet in a minimal lite mode by just skipping the block hash calculation. This is useful for testing purposes when the block hash is not needed.
```

2024-05-02 15:09 UTC, FabijanC commented on crates/starknet-devnet/src/cli.rs
> +    #[arg(value_name = "LITE_MODE")]
This has no effect for boolean flags, does it?

2024-05-02 15:09 UTC, FabijanC commented on scripts/benchmark/mint_benchmark.sh
> +ADDRESS=$2
Address needn't be a parameter

2024-05-02 15:09 UTC, FabijanC commented on scripts/benchmark/mint_benchmark.sh
> +done
Add a newline

2024-05-02 15:09 UTC, FabijanC commented on crates/starknet-devnet-core/src/starknet/mod.rs
> +        }
Can be shortened to `new_block.set_block_hash(if self.config.lite_mode { ... } else { ... })`

2024-05-02 15:09 UTC, FabijanC commented on crates/starknet-devnet-core/src/starknet/mod.rs
> +                "0x{:x}",
Can be `"{:#x}"`

2024-05-03 11:36 UTC, FabijanC approved these changes
Thanks!

2024-05-03 11:39 UTC, merged

2024-05-03 12:22 UTC, FabijanC commented
@lordshashank Please, in the future, execute the tests to ensure the CI workflow passes. I will fix the failure coming from the merge of this PR.

2024-05-03 16:02 UTC, lordshashank commented
Really really sorry, I was thinking to do that after all the issues in pr were resolved, just forgot it at the end. Would surely keep in mind from next time.