Docs misstakes fix
0xSpaceShard/starknet-devnet-rs pull request #556
Opened 2024-07-17 08:46 UTC by kkawula

## Usage related changes

## Development related changes

from_address

## Checklist:

- [ ] Checked out the [contribution guidelines](CONTRIBUTING.md)
- [ ] Applied formatting - `./scripts/format.sh`
- [ ] No linter errors - `./scripts/clippy_check.sh`
- [ ] No unused dependencies - `./scripts/check_unused_deps.sh`
- [ ] No spelling errors - `./scripts/check_spelling.sh`
- [ ] Performed code self-review
- [ ] Rebased to the latest commit of the target branch (or merged it into my branch)
    -   Once you make the PR reviewable, please prefer merging over rebasing
- [ ] Updated the docs if needed - `./website/README.md`
- [ ] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] Updated the tests if needed; all passing - [execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/main/.github/CONTRIBUTING.md#test-execution)

2024-07-17 13:57 UTC, FabijanC requested changes
I see you applied these fixes in the latest documentation version and the historic version 0.1.2. Either apply them only in the latest version or in all versions.

2024-07-19 11:25 UTC, kkawula commented
> I see you applied these fixes in the latest documentation version and the historic version 0.1.2. Either apply them only in the latest version or in all versions.

I left the changes in the latest version

2024-07-19 11:36 UTC, FabijanC commented on website/docs/postman.md
> -    "l2_contract_address": "0x00285ddb7e5c777b310d806b9b2a0f7c7ba0a41f12b420219209d97a3b7f25b2",
This should also be applied in L157.

2024-07-19 11:53 UTC, FabijanC approved these changes

2024-07-19 11:53 UTC, merged